[qpu]
name = "pfaff_v1"
location = "Pfaff Lab"
qubit_count = 4
topology = "linear"
qubits = [0,1,2,3]
exclusions = []
couplings = [[0,1], [1,2], [2,3]]

[network]
username = "default"
address = "localhost"
port = 50052
client_cert_dir = "./certs/clients"
server_cert = "./certs/ca.crt"
